// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R4A
// for dark (dark@development) on Wed Jun  6 21:29:46 2018

// Copyright (c) 2000-2018 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "ServiceProfiling_Functions.hh"

namespace ServiceProfiling__Functions {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const CHARSTRING cs_0(24, "{(.+) to (.+) step (.+)}");
static const unsigned char module_checksum[] = { 0xf2, 0xe7, 0x34, 0xda, 0x22, 0xf3, 0x16, 0x5e, 0xcf, 0x1e, 0xfc, 0xc4, 0x5e, 0x94, 0x0f, 0x58 };

/* Global variable definitions */

TTCN_Module module_object("ServiceProfiling_Functions", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 0LU, 0, post_init_module, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_6,
  current_runtime_version.requires_minor_version_4,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_1);

/* Bodies of functions, altsteps and testcases */

ServiceProfiling__Types::Parameter__Macro parseParameterMacros(const CHARSTRING& macro)
{
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 10 */
CHARSTRING regex__step(cs_0);
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 11 */
CHARSTRING regex__set(cs_0);
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 13 */
CHARSTRING beginning(regexp(macro, regex__step, 0, FALSE));
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 14 */
CHARSTRING end(regexp(macro, regex__step, 1, FALSE));
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 15 */
CHARSTRING step(regexp(macro, regex__step, 2, FALSE));
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 17 */
ServiceProfiling__Types::Parameter__Macro r;
r.beginning() = str2float(beginning);
r.end() = str2float(end);
r.step() = str2float(step);
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Functions.ttcn, line 22 */
return r;
}


/* Bodies of static functions */

static void pre_init_module()
{
ServiceProfiling__Types::module_object.pre_init_module();
module_object.add_function("parseParameterMacros", (genericfunc_t)&parseParameterMacros, NULL);
}

static void post_init_module()
{
ServiceProfiling__Types::module_object.post_init_module();
}


} /* end of namespace */
