// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R4A
// for dark (dark@development) on Wed May 23 18:53:43 2018

// Copyright (c) 2000-2018 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "ServiceProfiling_Templates.hh"

namespace ServiceProfiling__Templates {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const CHARSTRING cs_1(22, "${0.1 to 1.0 step 0.1}"),
cs_6(11, "${128, 256}"),
cs_3(15, "${64, 128, 256}"),
cs_2('0'),
cs_5(3, "0,1"),
cs_9(5, "iperf"),
cs_10(21, "iperf -c iperf-server"),
cs_13(8, "iperf -s"),
cs_7(12, "iperf-client"),
cs_11(12, "iperf-server"),
cs_4(5, "nginx"),
cs_8(8, "ns:input"),
cs_12(9, "ns:output"),
cs_14(17, "serviceprofiling1"),
cs_0(5, "snort"),
cs_15(24, "sonata-empty-service.son");
static const unsigned char module_checksum[] = { 0xf2, 0x5c, 0x2a, 0xc6, 0x1f, 0x32, 0xef, 0x24, 0x8e, 0xcd, 0xdf, 0x44, 0xcc, 0x22, 0x19, 0x24 };

/* Global variable definitions */

static ServiceProfiling__Types::ResourceConfigurations_template template_rcfg;
const ServiceProfiling__Types::ResourceConfigurations_template& rcfg = template_rcfg;
static ServiceProfiling__Types::MeasuringPointVNFs_template template_mpvnf;
const ServiceProfiling__Types::MeasuringPointVNFs_template& mpvnf = template_mpvnf;
static ServiceProfiling__Types::ServiceProfilingExperiment_template template_spexperiment;
const ServiceProfiling__Types::ServiceProfilingExperiment_template& spexperiment = template_spexperiment;
TTCN_Module module_object("ServiceProfiling_Templates", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 0LU, 0, post_init_module, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_6,
  current_runtime_version.requires_minor_version_4,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_1);

/* Bodies of static functions */

static void pre_init_module()
{
ServiceProfiling__Types::module_object.pre_init_module();
}

static void post_init_module()
{
ServiceProfiling__Types::module_object.post_init_module();
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Templates.ttcn, line 4 */
template_rcfg.set_size(2);
{
ServiceProfiling__Types::ResourceConfiguration_template& tmp_0 = template_rcfg[0];
tmp_0.function__id() = cs_0;
tmp_0.cpu__time() = cs_1;
tmp_0.cpu__set() = cs_2;
tmp_0.max__mem() = cs_3;
}
{
ServiceProfiling__Types::ResourceConfiguration_template& tmp_1 = template_rcfg[1];
tmp_1.function__id() = cs_4;
tmp_1.cpu__time() = cs_1;
tmp_1.cpu__set() = cs_5;
tmp_1.max__mem() = cs_6;
}
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Templates.ttcn, line 15 */
template_mpvnf.set_size(2);
{
ServiceProfiling__Types::MeasuringPointVNF_template& tmp_2 = template_mpvnf[0];
tmp_2.name() = cs_7;
tmp_2.connection__point() = cs_8;
tmp_2.image() = cs_9;
tmp_2.cmd() = cs_10;
}
{
ServiceProfiling__Types::MeasuringPointVNF_template& tmp_3 = template_mpvnf[1];
tmp_3.name() = cs_11;
tmp_3.connection__point() = cs_12;
tmp_3.image() = cs_9;
tmp_3.cmd() = cs_13;
}
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Templates.ttcn, line 26 */
template_spexperiment.name() = cs_14;
template_spexperiment.repetitions() = 10;
template_spexperiment.profiling__timeout() = 300;
template_spexperiment.service__name() = cs_15;
template_spexperiment.resourcecfgs() = rcfg;
template_spexperiment.MpVNFs() = mpvnf;
}


} /* end of namespace */
