// This C++ header file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R4A
// for dark (dark@development) on Wed May 23 18:53:43 2018

// Copyright (c) 2000-2018 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

#ifndef ServiceProfiling__Templates_HH
#define ServiceProfiling__Templates_HH

#ifdef TITAN_RUNTIME_2
#error Generated code does not match with used runtime.\
 Code was generated without -R option but -DTITAN_RUNTIME_2 was used.
#endif

/* Header file includes */

#include <TTCN3.hh>
#include "ServiceProfiling_Types.hh"

#if TTCN3_VERSION != 60400
#error Version mismatch detected.\
 Please check the version of the TTCN-3 compiler and the base library.\
 Run make clean and rebuild the project if the version of the compiler changed recently.
#endif

#ifndef LINUX
#error This file should be compiled on LINUX
#endif

namespace ServiceProfiling__Templates {

/* Global variable declarations */

extern const ServiceProfiling__Types::ResourceConfigurations_template& rcfg;
extern const ServiceProfiling__Types::MeasuringPointVNFs_template& mpvnf;
extern const ServiceProfiling__Types::ServiceProfilingExperiment_template& spexperiment;
extern TTCN_Module module_object;

} /* end of namespace */

#endif
