// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R4A
// for dark (dark@development) on Wed May 23 18:53:43 2018

// Copyright (c) 2000-2018 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "ServiceProfiling_Functions.hh"

namespace ServiceProfiling__Functions {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const unsigned char module_checksum[] = { 0x32, 0x82, 0x46, 0x74, 0xca, 0x00, 0x9f, 0x7e, 0x89, 0x63, 0xfb, 0x0f, 0xdf, 0x72, 0x01, 0x7a };

/* Global variable definitions */

TTCN_Module module_object("ServiceProfiling_Functions", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 0LU, 0, post_init_module, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_6,
  current_runtime_version.requires_minor_version_4,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_1);

/* Bodies of static functions */

static void pre_init_module()
{
ServiceProfiling__Types::module_object.pre_init_module();
}

static void post_init_module()
{
ServiceProfiling__Types::module_object.post_init_module();
}


} /* end of namespace */
