// This C++ source file was generated by the TTCN-3 compiler
// of the TTCN-3 Test Executor version CRL 113 200/6 R4A
// for dark (dark@development) on Thu Jun  7 12:01:06 2018

// Copyright (c) 2000-2018 Ericsson Telecom AB

// Do not edit this file unless you know what you are doing.

/* Including header files */

#include "ServiceProfiling_Templates.hh"

namespace ServiceProfiling__Templates {

/* Prototypes of static functions */

static void pre_init_module();
static void post_init_module();

/* Literal string constants */

static const CHARSTRING cs_1(22, "${0.1 to 1.0 step 0.1}"),
cs_3(15, "${64, 128, 256}"),
cs_2('0'),
cs_4(6, "client"),
cs_7(21, "iperf -c iperf-server"),
cs_10(8, "iperf -s"),
cs_8(6, "server"),
cs_11(17, "serviceprofiling1"),
cs_0(9, "snort_vnf"),
cs_5(15, "snort_vnf:input"),
cs_9(16, "snort_vnf:output"),
cs_12(24, "sonata-snort-service.son"),
cs_6(27, "sonatanfv/sonata-iperf3-vnf");
static const unsigned char module_checksum[] = { 0xd9, 0x69, 0x19, 0x51, 0x97, 0x12, 0x24, 0xb5, 0x82, 0xa3, 0x0c, 0xf6, 0x25, 0x0e, 0x9d, 0x95 };

/* Global variable definitions */

static ServiceProfiling__Types::ResourceConfigurations_template template_rcfg;
const ServiceProfiling__Types::ResourceConfigurations_template& rcfg = template_rcfg;
static ServiceProfiling__Types::MeasuringPointVNFs_template template_mpvnf;
const ServiceProfiling__Types::MeasuringPointVNFs_template& mpvnf = template_mpvnf;
static ServiceProfiling__Types::ServiceProfilingExperiment_template template_spexperiment;
const ServiceProfiling__Types::ServiceProfilingExperiment_template& spexperiment = template_spexperiment;
TTCN_Module module_object("ServiceProfiling_Templates", __DATE__, __TIME__, module_checksum, pre_init_module, NULL, 0U, 4294967295U, 4294967295U, 4294967295U, NULL, 0LU, 0, post_init_module, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

static const RuntimeVersionChecker ver_checker(  current_runtime_version.requires_major_version_6,
  current_runtime_version.requires_minor_version_4,
  current_runtime_version.requires_patch_level_0,  current_runtime_version.requires_runtime_1);

/* Bodies of static functions */

static void pre_init_module()
{
ServiceProfiling__Types::module_object.pre_init_module();
}

static void post_init_module()
{
ServiceProfiling__Types::module_object.post_init_module();
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Templates.ttcn, line 4 */
template_rcfg.set_size(1);
{
ServiceProfiling__Types::ResourceConfiguration_template& tmp_0 = template_rcfg[0];
tmp_0.function__id() = cs_0;
tmp_0.cpu__time() = cs_1;
tmp_0.cpu__set() = cs_2;
tmp_0.max__mem() = cs_3;
}
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Templates.ttcn, line 11 */
template_mpvnf.set_size(2);
{
ServiceProfiling__Types::MeasuringPointVNF_template& tmp_1 = template_mpvnf[0];
tmp_1.name() = cs_4;
tmp_1.connection__point() = cs_5;
tmp_1.image() = cs_6;
tmp_1.cmd() = cs_7;
}
{
ServiceProfiling__Types::MeasuringPointVNF_template& tmp_2 = template_mpvnf[1];
tmp_2.name() = cs_8;
tmp_2.connection__point() = cs_9;
tmp_2.image() = cs_6;
tmp_2.cmd() = cs_10;
}
/* /home/dark/eclipse-workspace/nfv-service-profiling/src/ServiceProfiling_Templates.ttcn, line 22 */
template_spexperiment.name() = cs_11;
template_spexperiment.repetitions() = 10;
template_spexperiment.profiling__timeout() = 300;
template_spexperiment.service__name() = cs_12;
template_spexperiment.resourcecfgs() = rcfg;
template_spexperiment.MpVNFs() = mpvnf;
}


} /* end of namespace */
