package:
  description: "Haproxy, nginxlb and nginx SFC"
  maintainer: "Christian Dröge, mail@cdroege.de"
  name: tsp-haproxy-nginxlb-nginx-service
  vendor: de.cdroege
  version: '0.1'
descriptor_extension: "yml"
version: '0.5'
